services:
  comfyui:
    image: yanwk/comfyui-boot:cu128-megapak

    container_name: comfyui

    restart: unless-stopped

    gpus: all

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CLI_ARGS=--listen

    ports:
      - "8188:8188"

    volumes:
      - /mnt/s/raj-storage/models/comfy:/root/ComfyUI/models
      - /mnt/s/raj-storage/outputs/comfy:/root/ComfyUI/output
      - /mnt/s/raj-storage/cache:/root/.cache
      - /mnt/s/raj-storage/workflows:/root/ComfyUI/user/default/workflows

    networks:
      - raj-cloudflare_proxy_tunnel

networks:
  raj-cloudflare_proxy_tunnel:
    external: true
