services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    volumes:
      - /mnt/s/raj-storage/open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://llama-cpp:8080
      - OPENAI_API_BASE_URL=http://llama-cpp:8080/v1
    networks:
      - raj-cloudflare_proxy_tunnel

networks:
  raj-cloudflare_proxy_tunnel:
    external: true
